# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-03 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='badge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
