# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-03-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
