# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sale_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=50),
        ),
    ]
