# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-10-16 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180213_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Delivery'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ean',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
